### ISSUE TITLE
Hortense ReFrame 3.10.1

### ISSUE THREAD

**Issue by Lewih** [vscentrum/vsc-test-suite#18]
Hortense still has no installation of ReFrame 3.10.1.

**Comment by boegel** [comment]
I'm looking into that right now, will close this issue when it's in place and available via `module load`...

**Comment by boegel** [comment]
`ReFrame/3.10.1` is now available on Tier-1 Hortense as a part of the central software stack:

```
$ module avail ReFrame
------- /readonly/dodrio/apps/RHEL8/zen2-ib/modules/all ------
   ReFrame/3.9.1    ReFrame/3.10.1 (D)

$ module load ReFrame/3.10.1
$ reframe --version
3.10.1
```
