### ISSUE TITLE
use VSC_SCRATCH for prefix and output

### ISSUE THREAD

**Issue by smoors** [vscentrum/vsc-test-suite#40]
writing into $HOME may result in performance degradation due to slow NFS mounts.
see also https://github.com/vscentrum/vsc-test-suite/pull/32#issuecomment-1200405676

**Comment by Lewih** [comment]
@smoors I agree to change the output and prefix, but I propose to do it in the next iteration --> #39

**Comment by Lewih** [comment]
In #39 I am using `/apps/antwerpen/reframe/logs` and in some tests vscscratch is used for tmp data
