### ISSUE TITLE
Allow apptainer as an alternative for singularity

### ISSUE THREAD

**Issue by stevenvdb** [vscentrum/vsc-test-suite#42]
We made the switch from singularity to apptainer. We still make the singularity command available, by symlinking to apptainer. However, `singularity --version` now gives `apptainer version 1.0.3-1`  which makes `VSCToolVersionTest_singularity` fail. Can we adapt the test so it also passes if `apptainer=1.0.3` is found?

**Comment by Lewih** [comment]
You are not the only ones moving to apptainer ;) .

surely we can.

**Comment by boegel** [comment]
This is also relevant for UGent Tier-2 + Tier-1 Hortense, where we have also migrated to Apptainer.
